# Generated by Django 4.0.4 on 2022-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('car_date', models.DateField()),
            ],
        ),
    ]
