# Generated by Django 4.0.4 on 2022-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
