# Generated by Django 4.0.4 on 2022-06-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_cars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=3)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.cars')),
            ],
        ),
    ]
