# Generated by Django 4.0.4 on 2022-06-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
