# Generated by Django 4.0.4 on 2022-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('r_username', models.CharField(max_length=20)),
                ('r_email', models.CharField(max_length=150)),
                ('r_number', models.CharField(max_length=10)),
            ],
        ),
    ]
