# Generated by Django 4.0.4 on 2022-06-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
