# Generated by Django 4.0.4 on 2022-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rent',
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='days',
            field=models.CharField(default='', max_length=3),
        ),
    ]
